### ISSUE TITLE
Can I globaly change the output format types ?

### ISSUE THREAD

**Issue by kidpollo** [nesquena/rabl#336]
Hi!

I am getting

```
"last_activity_at": "2012-08-21T22:29:38Z"
```

For date time fields. Is there a way to change the output format fro all DateTime attributes? What If I want a format like "2012-08-21 22:29:38 UTC" but for all DateTimes in all my templates.

Could it be done per class type?

Thaks

**Comment by knu** [comment]
When using oj with rabl, you'd better override `as_json` instead of `to_json`, because Oj.dump tries `as_json` prior to `to_json`.
For example, the `ActiveSupport::TimeWithZone` class has `as_json` defined, so overriding its `to_json` method does not affect how Oj dumps its instances.  You need to override `as_json` instead.
```
class ActiveSupport::TimeWithZone
  def as_json
    iso8601(6)
  end
end
```
It took me awhile to find this, so I thought it's worth sharing it here.
