### ISSUE TITLE
Option to camelize attributes

### ISSUE THREAD

**Issue by guilhermesimoes** [nesquena/rabl#469]
The standard in Ruby is using snake_case but in Javascript, arguably the main JSON consumer, the standard is camelCase. I would like my js projects to be a little more consistent so would you be open to an option that camelizes all attributes?

**Comment by petRUShka** [comment]
Is there some support of camelCase in rabl?

**Comment by gakshay** [comment]
Just tried with this option:

`
Rabl.configure do |config|
  config.xml_options = { :camelize  => true, :skip_types => false }
end
`

It worked but in CamelCase not in camelCase..

**Comment by petRUShka** [comment]
I'm speaking mostly on `json_options`. Is there something for JSON?

**Comment by gakshay** [comment]
Okay..unable to figure out something like json_options is provided out of the box..

**Comment by nitzanav** [comment]
+1

I would love to have an option to enable JSON transition to camelCase, in order to conform JS client naming conventions.

The [Google JSON guide](http://google-styleguide.googlecode.com/svn/trunk/jsoncstyleguide.xml?showone=Property_Name_Format#Property_Name_Format) states: "Property names must be camel-cased, ascii strings"
